version: '3'

services:
  cezerin-api:
    command: "npm run dev"

  cezerin-store:
#    command: "npm run dev:watch"

  cezerin-admin:
#    command: "npm run start -- --host 0.0.0.0"

  caddy:
    environment:
      - APP_DOMAIN=${APP_DOMAIN}:80